version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  back:
    container_name: back
    build:
      context: ./back
    command: python /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back/app:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=your_db_name
      - DATABASE_USER=your_db_user
      - DATABASE_PASSWORD=your_db_password
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

  front:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - back

volumes:
  postgres_data:
