# Generated by Django 5.2.5 on 2025-08-17 21:39

import django.db.models.deletion
import real_estate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_realestateobject_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=real_estate.models.real_estate_image_upload_to)),
                ('alt', models.CharField(blank=True, default='', max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('real_estate_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='real_estate.realestateobject')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
