# Generated by Django 5.2.5 on 2025-08-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0003_realestateimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateobject',
            name='email',
            field=models.EmailField(default='default@example.com', help_text='Email used to verify ownership for deletion', max_length=255),
            preserve_default=False,
        ),
    ]
