# Generated by Django 5.2.5 on 2025-08-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0004_realestateobject_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateobject',
            name='deletion_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
