# Generated by Django 5.2.5 on 2025-08-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0005_realestateobject_deletion_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateobject',
            name='coordinates',
            field=models.CharField(default=49.9936727, max_length=512),
            preserve_default=False,
        ),
    ]
