# Generated by Django 5.2.5 on 2025-08-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0006_realestateobject_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestateobject',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='realestateobject',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='realestateobject',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
